title: Name  # Jay Kleine

# logo: 1.png # Use a relative path to logo image

description: Computer Science Resume and Portfolio. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
