title: Jay William Kleine

# logo: 1.png # Use a relative path to logo image

description: Computer Science Resume and Portfolio. # Fix hyphenation 

show_downloads: True # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag

email: jaykleine@gmail.com 
